export const POS_BILL_LIST_I18N = {
  title: "posCashier.billListDialog.title",
  close: "posCashier.billListDialog.close",
  newBill: "posCashier.billListDialog.newBill",
  tabOpen: "posCashier.billListDialog.tabOpen",
  tabCancelled: "posCashier.billListDialog.tabCancelled",
  tabProductVoids: "posCashier.billListDialog.tabProductVoids",
  tabPaidRefunds: "posCashier.billListDialog.tabPaidRefunds",
  searchOpen: "posCashier.billListDialog.searchOpen",
  searchCancelled: "posCashier.billListDialog.searchCancelled",
  searchVoids: "posCashier.billListDialog.searchVoids",
  searchPaid: "posCashier.billListDialog.searchPaid",
  colTable: "posCashier.billListDialog.colTable",
  colCustomer: "posCashier.billListDialog.colCustomer",
  colGroup: "posCashier.billListDialog.colGroup",
  colWaiter: "posCashier.billListDialog.colWaiter",
  colTime: "posCashier.billListDialog.colTime",
  colSync: "posCashier.billListDialog.colSync",
  colAction: "posCashier.billListDialog.colAction",
  colReason: "posCashier.billListDialog.colReason",
  colProduct: "posCashier.billListDialog.colProduct",
  colQty: "posCashier.billListDialog.colQty",
  emptyOpen: "posCashier.billListDialog.emptyOpen",
  emptyCancelled: "posCashier.billListDialog.emptyCancelled",
  emptyVoids: "posCashier.billListDialog.emptyVoids",
  emptyPaid: "posCashier.billListDialog.emptyPaid",
  cancelBill: "posCashier.billListDialog.cancelBill",
  fulfillBill: "posCashier.billListDialog.fulfillBill",
  cancelSuccess: "posCashier.billListDialog.cancelSuccess",
  cancelReasonTitle: "posCashier.billListDialog.cancelReasonTitle",
  voidReasonTitle: "posCashier.billListDialog.voidReasonTitle",
  voidReasonQtyReduced: "posCashier.billListDialog.voidReasonQtyReduced",
  reasonPlaceholder: "posCashier.billListDialog.reasonPlaceholder",
  reasonRequired: "posCashier.billListDialog.reasonRequired",
  confirm: "posCashier.billListDialog.confirm",
  cancel: "posCashier.billListDialog.cancel",
  newBillConfirm: "posCashier.billListDialog.newBillConfirm",
  needTableToSave: "posCashier.billListDialog.needTableToSave",
  refundStock: "posCashier.billListDialog.refundStock",
  refundedBadge: "posCashier.billListDialog.refundedBadge",
  refundSuccess: "posCashier.billListDialog.refundSuccess",
  refundError: "posCashier.billListDialog.refundError",
  synced: "posCashier.billListDialog.synced",
} as const;

export type PosBillListTab = "open" | "cancelled" | "product_voids" | "paid_refunds";

export const POS_BILL_REASON_MIN_LEN = 3;
