export const POS_ITEM_CUSTOMIZE_I18N = {
  cancel: "posCashier.itemCustomize.cancel",
  save: "posCashier.itemCustomize.save",
  variant: "posCashier.itemCustomize.variant",
  pickOne: "posCashier.itemCustomize.pickOne",
  pickMany: "posCashier.itemCustomize.pickMany",
  qty: "posCashier.itemCustomize.qty",
  discount: "posCashier.itemCustomize.discount",
  salesType: "posCashier.itemCustomize.salesType",
  loading: "posCashier.itemCustomize.loading",
  customAmount: "posCashier.itemCustomize.customAmount",
  optionOutOfStock: "posCashier.itemCustomize.optionOutOfStock",
  notes: "posCashier.itemCustomize.notes",
  notesOptional: "posCashier.itemCustomize.notesOptional",
  notesPlaceholder: "posCashier.itemCustomize.notesPlaceholder",
  notesAdd: "posCashier.itemCustomize.notesAdd",
  notesEdit: "posCashier.itemCustomize.notesEdit",
} as const;
