export const POS_PAY_SUCCESS_I18N = {
  paid: "posCashier.paySuccessScreen.paid",
  change: "posCashier.paySuccessScreen.change",
  methodCash: "posCashier.paySuccessScreen.methodCash",
  methodEwallet: "posCashier.paySuccessScreen.methodEwallet",
  methodTransfer: "posCashier.paySuccessScreen.methodTransfer",
  emailPlaceholder: "posCashier.paySuccessScreen.emailPlaceholder",
  smsPlaceholder: "posCashier.paySuccessScreen.smsPlaceholder",
  namePlaceholder: "posCashier.paySuccessScreen.namePlaceholder",
  send: "posCashier.paySuccessScreen.send",
  print: "posCashier.paySuccessScreen.print",
  newTransaction: "posCashier.paySuccessScreen.newTransaction",
  digitalDisabled: "posCashier.paySuccessScreen.digitalDisabled",
  shareEmailOff: "posCashier.paySuccessScreen.shareEmailOff",
  shareSmsOff: "posCashier.paySuccessScreen.shareSmsOff",
  invalidEmail: "posCashier.paySuccessScreen.invalidEmail",
  invalidPhone: "posCashier.paySuccessScreen.invalidPhone",
  sendSuccess: "posCashier.paySuccessScreen.sendSuccess",
  sendError: "posCashier.paySuccessScreen.sendError",
  printError: "posCashier.paySuccessScreen.printError",
  pickTable: "posCashier.paySuccessScreen.pickTable",
  tableAssigned: "posCashier.paySuccessScreen.tableAssigned",
  needTable: "posCashier.paySuccessScreen.needTable",
} as const;
