export const POS_SELECT_TABLE_I18N = {
  title: "posCashier.selectTable.title",
  cancel: "posCashier.selectTable.cancel",
  saveAsBill: "posCashier.selectTable.saveAsBill",
  continue: "posCashier.selectTable.continue",
  occupied: "posCashier.selectTable.occupied",
  emptyGroup: "posCashier.selectTable.emptyGroup",
  needGroup: "posCashier.selectTable.needGroup",
  walkInName: "posCashier.selectTable.walkInName",
  saved: "posCashier.selectTable.saved",
  saveError: "posCashier.selectTable.saveError",
  pickBill: "posCashier.sharedTable.pickBill",
  newBillOnTable: "posCashier.sharedTable.newBillOnTable",
  noCapacity: "posCashier.sharedTable.noCapacity",
  sharedCapacity: "posCashier.sharedTable.capacity",
  sharedBills: "posCashier.sharedTable.bills",
  sharedSessionPax: "posCashier.sharedTable.sessionPax",
  remainingPax: "posCashier.sharedTable.remainingPax",
  multipleOpenError: "posCashier.sharedTable.multipleOpenError",
} as const;
