import type { MetricDef } from "@/google-ads/metrics/googleAdsMetricsCatalogTypes";
import { ALL_ENTITIES } from "@/google-ads/metrics/googleAdsMetricsCatalogTypes";

/** GAQL-valid metrics only; English labels match Google Ads UI. */
export const METRIC_CATALOG: MetricDef[] = [
  {
    key: "impressions",
    label: "Impr.",
    category: "performance",
    gaqlField: "metrics.impressions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Number of times your ads were shown.",
    recommendedFor: ALL_ENTITIES,
  },
  {
    key: "clicks",
    label: "Clicks",
    category: "performance",
    gaqlField: "metrics.clicks",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Number of clicks.",
    recommendedFor: ALL_ENTITIES,
  },
  {
    key: "ctr",
    label: "CTR",
    category: "performance",
    gaqlField: "metrics.ctr",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Click-through rate.",
    recommendedFor: ALL_ENTITIES,
  },
  {
    key: "spent",
    label: "Cost",
    category: "performance",
    gaqlField: "metrics.cost_micros",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Total cost.",
  },
  {
    key: "avg_cpc",
    label: "Avg. CPC",
    category: "performance",
    gaqlField: "metrics.average_cpc",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Average cost per click.",
    recommendedFor: ["campaign", "ad_group", "keyword"],
  },
  {
    key: "avg_cpm",
    label: "Avg. CPM",
    category: "performance",
    gaqlField: "metrics.average_cpm",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Average cost per 1000 impressions.",
  },
  {
    key: "avg_cpv",
    label: "Avg. CPV",
    category: "performance",
    gaqlField: "metrics.average_cpv",
    valueKind: "micros",
    entities: ["campaign", "ad_group", "ad"],
    sortable: false,
    description: "Average cost per view.",
  },
  {
    key: "avg_cost",
    label: "Avg. cost",
    category: "performance",
    gaqlField: "metrics.average_cost",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Average cost per interaction.",
  },
  {
    key: "engagements",
    label: "Engagements",
    category: "performance",
    gaqlField: "metrics.engagements",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Number of engagements.",
  },
  {
    key: "engagement_rate",
    label: "Engagement rate",
    category: "performance",
    gaqlField: "metrics.engagement_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Engagement rate.",
  },
  {
    key: "interactions",
    label: "Interactions",
    category: "performance",
    gaqlField: "metrics.interactions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Number of interactions.",
  },
  {
    key: "interaction_rate",
    label: "Interaction rate",
    category: "performance",
    gaqlField: "metrics.interaction_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Interaction rate.",
  },
  {
    key: "invalid_clicks",
    label: "Invalid clicks",
    category: "performance",
    gaqlField: "metrics.invalid_clicks",
    valueKind: "count",
    entities: ["campaign", "ad_group", "ad"],
    sortable: true,
    description: "Invalid clicks.",
  },
  {
    key: "invalid_click_rate",
    label: "Invalid click rate",
    category: "performance",
    gaqlField: "metrics.invalid_click_rate",
    valueKind: "rate",
    entities: ["campaign", "ad_group", "ad"],
    sortable: false,
    description: "Invalid click rate.",
  },
  {
    key: "video_views",
    label: "Video views",
    category: "performance",
    gaqlField: "metrics.video_views",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Video views.",
  },
  {
    key: "video_view_rate",
    label: "Video view rate",
    category: "performance",
    gaqlField: "metrics.video_view_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Video view rate.",
  },
  {
    key: "active_view_impressions",
    label: "Active view impr.",
    category: "performance",
    gaqlField: "metrics.active_view_impressions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Active view impressions.",
  },
  {
    key: "active_view_cpm",
    label: "Active view CPM",
    category: "performance",
    gaqlField: "metrics.active_view_cpm",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Active view average CPM.",
  },
  {
    key: "conversions",
    label: "Conversions",
    category: "conversions",
    gaqlField: "metrics.conversions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversions.",
    recommendedFor: ALL_ENTITIES,
  },
  {
    key: "conv_rate",
    label: "Conv. rate",
    category: "conversions",
    gaqlField: "metrics.conversions_from_interactions_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion rate.",
    recommendedFor: ALL_ENTITIES,
  },
  {
    key: "conv_value",
    label: "Conv. value",
    category: "conversions",
    gaqlField: "metrics.conversions_value",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion value.",
  },
  {
    key: "cost_per_conv",
    label: "Cost / conv.",
    category: "conversions",
    gaqlField: "metrics.cost_per_conversion",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Cost per conversion.",
    recommendedFor: ["campaign", "ad_group", "keyword"],
  },
  {
    key: "value_per_conv",
    label: "Value / conv.",
    category: "conversions",
    gaqlField: "metrics.value_per_conversion",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Value per conversion.",
  },
  {
    key: "all_conversions",
    label: "All conv.",
    category: "conversions",
    gaqlField: "metrics.all_conversions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "All conversions.",
  },
  {
    key: "all_conv_rate",
    label: "All conv. rate",
    category: "conversions",
    gaqlField: "metrics.all_conversions_from_interactions_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "All conversions rate.",
  },
  {
    key: "all_conv_value",
    label: "All conv. value",
    category: "conversions",
    gaqlField: "metrics.all_conversions_value",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "All conversion value.",
  },
  {
    key: "cost_per_all_conv",
    label: "Cost / all conv.",
    category: "conversions",
    gaqlField: "metrics.cost_per_all_conversions",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Cost per all conversions.",
  },
  {
    key: "view_through_conversions",
    label: "View-through conv.",
    category: "conversions",
    gaqlField: "metrics.view_through_conversions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "View-through conversions.",
  },
  {
    key: "cross_device_conversions",
    label: "Cross-device conv.",
    category: "conversions",
    gaqlField: "metrics.cross_device_conversions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Cross-device conversions.",
  },
  {
    key: "conv_value_per_click",
    label: "Conv. value / click",
    category: "conversions",
    gaqlField: "metrics.conversions_value_per_click",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Conversion value per click.",
  },
  {
    key: "conv_value_per_cost",
    label: "Conv. value / cost",
    category: "conversions",
    gaqlField: "metrics.conversions_value_per_cost",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion value per cost.",
  },
  {
    key: "current_model_conversions",
    label: "Conversions (current model)",
    category: "attribution",
    gaqlField: "metrics.current_model_attributed_conversions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversions using the current attribution model.",
  },
  {
    key: "current_model_conv_rate",
    label: "Conv. rate (current model)",
    category: "attribution",
    gaqlField: "metrics.current_model_attributed_conversions_from_interactions_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion rate (current model).",
  },
  {
    key: "current_model_conv_value",
    label: "Conv. value (current model)",
    category: "attribution",
    gaqlField: "metrics.current_model_attributed_conversions_value",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion value (current model).",
  },
  {
    key: "current_model_cost_per_conv",
    label: "Cost / conv. (current model)",
    category: "attribution",
    gaqlField: "metrics.cost_per_current_model_attributed_conversion",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Cost per conversion (current model).",
  },
  {
    key: "current_model_value_per_conv",
    label: "Value / conv. (current model)",
    category: "attribution",
    gaqlField: "metrics.value_per_current_model_attributed_conversion",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Value per conversion (current model).",
  },
  {
    key: "current_model_conv_value_per_cost",
    label: "Conv. value / cost (current model)",
    category: "attribution",
    gaqlField: "metrics.current_model_attributed_conversions_value_per_cost",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Conversion value per cost (current model).",
  },
  {
    key: "search_top_is",
    label: "Search top IS",
    category: "bid_simulator",
    gaqlField: "metrics.search_top_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search top impression share.",
  },
  {
    key: "search_abs_top_is",
    label: "Search abs. top IS",
    category: "bid_simulator",
    gaqlField: "metrics.search_absolute_top_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search absolute top impression share.",
  },
  {
    key: "search_impression_share",
    label: "Search impr. share",
    category: "competitive",
    gaqlField: "metrics.search_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search impression share.",
  },
  {
    key: "search_budget_lost_is",
    label: "Search lost IS (budget)",
    category: "competitive",
    gaqlField: "metrics.search_budget_lost_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search lost impression share (budget).",
  },
  {
    key: "search_rank_lost_is",
    label: "Search lost IS (rank)",
    category: "competitive",
    gaqlField: "metrics.search_rank_lost_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search lost impression share (rank).",
  },
  {
    key: "search_lost_top_is_rank",
    label: "Search lost top IS (rank)",
    category: "competitive",
    gaqlField: "metrics.search_rank_lost_top_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search lost top impression share (rank).",
  },
  {
    key: "search_lost_abs_top_is_rank",
    label: "Search lost abs. top IS (rank)",
    category: "competitive",
    gaqlField: "metrics.search_rank_lost_absolute_top_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Search lost absolute top impression share (rank).",
  },
  {
    key: "search_click_share",
    label: "Click share",
    category: "competitive",
    gaqlField: "metrics.search_click_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Click share.",
  },
  {
    key: "search_exact_match_is",
    label: "Search exact match IS",
    category: "competitive",
    gaqlField: "metrics.search_exact_match_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: false,
    description: "Search exact match impression share.",
  },
  {
    key: "content_impression_share",
    label: "Display impr. share",
    category: "competitive",
    gaqlField: "metrics.content_impression_share",
    valueKind: "fraction",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Display impression share.",
  },
  {
    key: "absolute_top_impr_pct",
    label: "Impr. (Abs. Top) %",
    category: "competitive",
    gaqlField: "metrics.absolute_top_impression_percentage",
    valueKind: "fraction",
    entities: ["campaign", "ad_group", "keyword"],
    sortable: true,
    description: "Impressions on absolute top.",
  },
  {
    key: "top_impr_pct",
    label: "Impr. (Top) %",
    category: "competitive",
    gaqlField: "metrics.top_impression_percentage",
    valueKind: "fraction",
    entities: ["campaign", "ad_group", "keyword"],
    sortable: true,
    description: "Impressions on top.",
  },
  {
    key: "measurable_impressions",
    label: "Measurable impr.",
    category: "viewability",
    gaqlField: "metrics.measurable_impressions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Measurable impressions.",
  },
  {
    key: "measurable_rate",
    label: "Measurable rate",
    category: "viewability",
    gaqlField: "metrics.measurable_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Measurable rate.",
  },
  {
    key: "measurable_cost",
    label: "Measurable cost",
    category: "viewability",
    gaqlField: "metrics.measurable_cost_micros",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Measurable cost.",
  },
  {
    key: "active_view_measurable_impressions",
    label: "Active view measurable impr.",
    category: "viewability",
    gaqlField: "metrics.active_view_measurable_impressions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Active view measurable impressions.",
  },
  {
    key: "active_view_measurable_cost",
    label: "Active view measurable cost",
    category: "viewability",
    gaqlField: "metrics.active_view_measurable_cost_micros",
    valueKind: "micros",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Active view measurable cost.",
  },
  {
    key: "historical_quality_score",
    label: "Quality score",
    category: "quality_score",
    gaqlField: "metrics.historical_quality_score",
    valueKind: "count",
    entities: ["campaign", "ad_group", "keyword"],
    sortable: true,
    description: "Historical quality score.",
  },
  {
    key: "phone_calls",
    label: "Phone calls",
    category: "call_details",
    gaqlField: "metrics.phone_calls",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Phone calls.",
  },
  {
    key: "phone_impressions",
    label: "Phone impr.",
    category: "call_details",
    gaqlField: "metrics.phone_impressions",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Phone impressions.",
  },
  {
    key: "phone_through_rate",
    label: "Phone-through rate",
    category: "call_details",
    gaqlField: "metrics.phone_through_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Phone-through rate.",
  },
  {
    key: "message_chats",
    label: "Message chats",
    category: "message_details",
    gaqlField: "metrics.message_chats",
    valueKind: "count",
    entities: ALL_ENTITIES,
    sortable: true,
    description: "Message chats.",
  },
  {
    key: "message_chat_rate",
    label: "Message chat rate",
    category: "message_details",
    gaqlField: "metrics.message_chat_rate",
    valueKind: "rate",
    entities: ALL_ENTITIES,
    sortable: false,
    description: "Message chat rate.",
  },
  {
    key: "gmail_forwards",
    label: "Gmail forwards",
    category: "gmail",
    gaqlField: "metrics.gmail_forwards",
    valueKind: "count",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Gmail forwards.",
  },
  {
    key: "gmail_saves",
    label: "Gmail saves",
    category: "gmail",
    gaqlField: "metrics.gmail_saves",
    valueKind: "count",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Gmail saves.",
  },
  {
    key: "gmail_secondary_clicks",
    label: "Gmail secondary clicks",
    category: "gmail",
    gaqlField: "metrics.gmail_secondary_clicks",
    valueKind: "count",
    entities: ["campaign", "ad_group"],
    sortable: true,
    description: "Gmail secondary clicks.",
  },
];
