/** i18n keys for Synckerja POS Table Map (runtime floor plan). */
export const POS_TABLE_MAP_I18N = {
  title: "posTableMap.title",
  vacant: "posTableMap.vacant",
  selectTable: "posTableMap.selectTable",
  emptyMap: "posTableMap.emptyMap",
  needGroup: "posTableMap.needGroup",
  setupHint: "posTableMap.setupHint",
  legendVacant: "posTableMap.legendVacant",
  legendOccupied: "posTableMap.legendOccupied",
  occupied: "posTableMap.occupied",
  duration: "posTableMap.duration",
  tableLabel: "posTableMap.tableLabel",
  walkIn: "posTableMap.walkIn",
  clearTable: "posTableMap.clearTable",
  menu: "posTableMap.menu",
  loading: "posTableMap.loading",
  sheetClose: "posTableMap.sheet.close",
  sheetPax: "posTableMap.sheet.pax",
  sheetViewOrder: "posTableMap.sheet.viewOrder",
  sheetPrintBill: "posTableMap.sheet.printBill",
  sheetDeleteBill: "posTableMap.sheet.deleteBill",
  sheetCreateOrder: "posTableMap.sheet.createOrder",
  sheetConfirmDelete: "posTableMap.sheet.confirmDelete",
  sheetDeleteSuccess: "posTableMap.sheet.deleteSuccess",
  sheetPrintSuccess: "posTableMap.sheet.printSuccess",
  sheetPrintError: "posTableMap.sheet.printError",
  sheetDeleteError: "posTableMap.sheet.deleteError",
  sheetEmptyBill: "posTableMap.sheet.emptyBill",
  sheetClearTable: "posTableMap.sheet.clearTable",
  sheetConfirmClear: "posTableMap.sheet.confirmClear",
  sheetClearSuccess: "posTableMap.sheet.clearSuccess",
  sheetClearError: "posTableMap.sheet.clearError",
  billListTitle: "posTableMap.billList.title",
} as const;
