export const CASHIER_TICKET_I18N = {
  qrTitle: "synckerjaOrder.cashierTicket.qrTitle",
  showCashier: "synckerjaOrder.cashierTicket.showCashier",
  table: "synckerjaOrder.cashierTicket.table",
  total: "synckerjaOrder.cashierTicket.total",
  statusWaiting: "synckerjaOrder.cashierTicket.statusWaiting",
  statusClaimed: "synckerjaOrder.cashierTicket.statusClaimed",
  statusPaid: "synckerjaOrder.cashierTicket.statusPaid",
  statusExpired: "synckerjaOrder.cashierTicket.statusExpired",
  backToMenu: "synckerjaOrder.cashierTicket.backToMenu",
  profileTitle: "synckerjaOrder.profile.title",
  loginGuest: "synckerjaOrder.profile.loginGuest",
  signIn: "synckerjaOrder.profile.signIn",
  signInSoon: "synckerjaOrder.profile.signInSoon",
  orderHistory: "synckerjaOrder.profile.orderHistory",
  language: "synckerjaOrder.profile.language",
  privacyPolicy: "synckerjaOrder.profile.privacyPolicy",
  historyEmpty: "synckerjaOrder.profile.historyEmpty",
  historyHint: "synckerjaOrder.profile.historyHint",
  ticketExpires: "synckerjaOrder.cashierTicket.ticketExpires",
  takeAway: "synckerjaOrder.checkout.takeAway",
  dineIn: "synckerjaOrder.checkout.dineIn",
  fromTable: "synckerjaOrder.checkout.fromTable",
  paidSuccess: "synckerjaOrder.cashierTicket.paidSuccess",
  orderAgain: "synckerjaOrder.cashierTicket.orderAgain",
  returnToMenuHint: "synckerjaOrder.cashierTicket.returnToMenuHint",
  backToMenuAddItems: "synckerjaOrder.cashierTicket.backToMenuAddItems",
  claimedCanAddItems: "synckerjaOrder.cashierTicket.claimedCanAddItems",
  expiredHint: "synckerjaOrder.cashierTicket.expiredHint",
  paidReadOnlyTitle: "synckerjaOrder.cashierTicket.paidReadOnlyTitle",
  expiredReadOnlyTitle: "synckerjaOrder.cashierTicket.expiredReadOnlyTitle",
  readOnlyHint: "synckerjaOrder.cashierTicket.readOnlyHint",
  paidReorderBanner: "synckerjaOrder.cashierTicket.paidReorderBanner",
  paidReorderDismiss: "synckerjaOrder.cashierTicket.paidReorderDismiss",
  detailTitle: "synckerjaOrder.cashierTicket.detailTitle",
  showQrCode: "synckerjaOrder.cashierTicket.showQrCode",
  orderedItems: "synckerjaOrder.cashierTicket.orderedItems",
  loadError: "synckerjaOrder.cashierTicket.loadError",
  retry: "synckerjaOrder.cashierTicket.retry",
} as const;

export type CashierTicketStatus = "pending" | "claimed" | "paid" | "expired" | "cancelled";
