/// <reference path="../edge-runtime.d.ts" />
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
// __INLINE_WA_TEMPLATE_GRAPH__
// Generated by scripts/sync-wa-template-graph.mjs — do not edit by hand.
export function countPlaceholders(text: string): number {
  return (text.match(/\{\{[^}]+\}\}/g) ?? []).length;
}

const MEDIA_HEADER_FORMATS = new Set(["IMAGE", "VIDEO", "DOCUMENT"]);

function extractHttpsHeaderMediaUrl(c: Record<string, unknown>): string | null {
  const ex = c.example;
  if (!ex || typeof ex !== "object") return null;
  const handles = (ex as { header_handle?: unknown }).header_handle;
  if (!Array.isArray(handles)) return null;
  for (const h of handles) {
    const s = String(h ?? "").trim();
    if (/^https?:\/\//i.test(s)) return s;
  }
  return null;
}

export type BuildGraphTemplateResult =
  | { ok: true; components: Array<Record<string, unknown>> }
  | { ok: false; reason: string };

export function isTemplateBuildFailure(
  result: BuildGraphTemplateResult,
): result is Extract<BuildGraphTemplateResult, { ok: false }> {
  return result.ok === false;
}

export type PostTemplateMessageResult =
  | { ok: true; wa_message_id: string; metaData: Record<string, unknown> }
  | { ok: false; status: number; body: string };

export function isPostTemplateMessageFailure(
  result: PostTemplateMessageResult,
): result is Extract<PostTemplateMessageResult, { ok: false }> {
  return result.ok === false;
}

/**
 * Build Graph API `template.components` from Meta template definition + flat parameter values.
 * Supports TEXT header/body placeholders and static media headers via example.header_handle HTTPS URL.
 */
export function buildGraphTemplateComponents(
  templateComponents: unknown[],
  parameterValues: unknown,
  options?: { allowMediaHeader?: boolean },
): BuildGraphTemplateResult {
  const allowMediaHeader = options?.allowMediaHeader !== false;
  const params = Array.isArray(parameterValues)
    ? parameterValues.map((x) => {
        const s = String(x ?? "").trim();
        return s.length > 0 ? s : "—";
      })
    : [];
  let idx = 0;
  const out: Array<Record<string, unknown>> = [];
  if (!Array.isArray(templateComponents)) return { ok: true, components: [] };

  for (const raw of templateComponents) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) continue;
    const c = raw as Record<string, unknown>;
    const type = String(c.type ?? "").toUpperCase();
    if (type === "HEADER") {
      const fmt = String(c.format ?? "TEXT").toUpperCase();
      if (MEDIA_HEADER_FORMATS.has(fmt)) {
        if (!allowMediaHeader) {
          return { ok: false, reason: "Media header templates are not supported for this send path yet." };
        }
        const text = String(c.text ?? "");
        const n = countPlaceholders(text);
        if (n > 0) {
          const parameters: { type: string; text: string }[] = [];
          for (let i = 0; i < n; i++) {
            const t = String(params[idx + i] ?? "—").slice(0, 1024);
            parameters.push({ type: "text", text: t.length ? t : "—" });
          }
          idx += n;
          out.push({ type: "header", parameters });
          continue;
        }
        const mediaUrl = extractHttpsHeaderMediaUrl(c);
        if (mediaUrl) {
          const fmtLower = fmt.toLowerCase();
          const paramType = fmtLower === "document" ? "document" : fmtLower === "video" ? "video" : "image";
          out.push({
            type: "header",
            parameters: [
              {
                type: paramType,
                [paramType]: { link: mediaUrl },
              },
            ],
          });
        }
        continue;
      }
      const text = String(c.text ?? "");
      const n = countPlaceholders(text);
      if (n === 0) continue;
      const parameters: { type: string; text: string }[] = [];
      for (let i = 0; i < n; i++) {
        const t = String(params[idx + i] ?? "—").slice(0, 1024);
        parameters.push({ type: "text", text: t.length ? t : "—" });
      }
      idx += n;
      out.push({ type: "header", parameters });
    } else if (type === "BODY") {
      const text = String(c.text ?? "");
      const n = countPlaceholders(text);
      if (n === 0) continue;
      const parameters: { type: string; text: string }[] = [];
      for (let i = 0; i < n; i++) {
        const t = String(params[idx + i] ?? "—").slice(0, 1024);
        parameters.push({ type: "text", text: t.length ? t : "—" });
      }
      idx += n;
      out.push({ type: "body", parameters });
    }
  }
  return { ok: true, components: out };
}

export function countTemplateParameterSlots(components: unknown[] | null | undefined): number {
  if (!Array.isArray(components)) return 0;
  let total = 0;
  for (const raw of components) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) continue;
    const c = raw as Record<string, unknown>;
    const type = String(c.type ?? "").toUpperCase();
    if (type === "HEADER") {
      const fmt = String(c.format ?? "").toUpperCase();
      if (MEDIA_HEADER_FORMATS.has(fmt)) {
        total += countPlaceholders(String(c.text ?? ""));
        continue;
      }
      total += countPlaceholders(String(c.text ?? ""));
    } else if (type === "BODY") {
      total += countPlaceholders(String(c.text ?? ""));
    }
  }
  return total;
}

/** Human-readable outbound body for whatsapp_messages.storage */
export function renderTemplateBodyPreview(
  templateName: string,
  templateComponents: unknown[] | null | undefined,
  parameterValues: unknown,
): string {
  const params = Array.isArray(parameterValues) ? parameterValues.map((x) => String(x ?? "").trim()) : [];
  let idx = 0;
  const parts: string[] = [`[Template: ${templateName}]`];
  if (!Array.isArray(templateComponents)) return parts.join("\n");
  for (const raw of templateComponents) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) continue;
    const c = raw as Record<string, unknown>;
    const type = String(c.type ?? "").toUpperCase();
    if (type === "HEADER") {
      const fmt = String(c.format ?? "TEXT").toUpperCase();
      if (MEDIA_HEADER_FORMATS.has(fmt)) {
        parts.push(`[${fmt}]`);
        const n = countPlaceholders(String(c.text ?? ""));
        for (let i = 0; i < n; i++) idx++;
        continue;
      }
      let text = String(c.text ?? "");
      const n = countPlaceholders(text);
      for (let i = 0; i < n; i++) {
        const val = params[idx++] ?? "—";
        text = text.replace(/\{\{[^}]+\}\}/, val);
      }
      if (text.trim()) parts.push(text.trim());
    } else if (type === "BODY") {
      let text = String(c.text ?? "");
      const n = countPlaceholders(text);
      for (let i = 0; i < n; i++) {
        const val = params[idx++] ?? "—";
        text = text.replace(/\{\{[^}]+\}\}/, val);
      }
      if (text.trim()) parts.push(text.trim());
    }
  }
  return parts.join("\n").slice(0, 4090);
}

export const META_API_BASE = "https://graph.facebook.com/v18.0";

export async function postTemplateMessage(
  phoneNumberId: string,
  accessToken: string,
  toDigits: string,
  templateName: string,
  templateLanguage: string,
  components: Array<Record<string, unknown>>,
): Promise<PostTemplateMessageResult> {
  const url = `${META_API_BASE}/${encodeURIComponent(phoneNumberId)}/messages`;
  const template: Record<string, unknown> = {
    name: templateName,
    language: { code: templateLanguage },
  };
  if (components.length > 0) template.components = components;

  let lastText = "";
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messaging_product: "whatsapp",
        to: toDigits,
        type: "template",
        template,
      }),
    });
    lastText = await res.text();
    if (res.status === 429 || (res.status >= 500 && res.status <= 599)) {
      await new Promise((r) => setTimeout(r, 650 * (attempt + 1)));
      continue;
    }
    if (!res.ok) return { ok: false, status: res.status, body: lastText.slice(0, 2000) };
    let json: Record<string, unknown> = {};
    try {
      json = JSON.parse(lastText) as Record<string, unknown>;
    } catch {
      return { ok: false, status: res.status, body: lastText.slice(0, 2000) };
    }
    const messages = json?.messages as unknown[] | undefined;
    const first = messages?.[0] as Record<string, unknown> | undefined;
    const mid = first?.id != null ? String(first.id).trim() : "";
    if (!mid) return { ok: false, status: 500, body: lastText.slice(0, 2000) };
    return { ok: true, wa_message_id: mid, metaData: json };
  }
  return { ok: false, status: 429, body: lastText.slice(0, 2000) };
}
// __INLINE_WA_TEMPLATE_GRAPH_END__

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

function digitsOnly(to: string): string {
  return String(to ?? "").replace(/\D/g, "");
}

function parseWabaExpirationUnixSeconds(meta: Record<string, unknown>): number | null {
  const messages = meta.messages as unknown[] | undefined;
  const first = messages?.[0] as Record<string, unknown> | undefined;
  const conv = first?.conversation as { expiration_timestamp?: string | number } | undefined;
  const raw = conv?.expiration_timestamp;
  if (raw == null) return null;
  const n = typeof raw === "string" ? Number.parseInt(raw, 10) : Number(raw);
  return Number.isFinite(n) && n > 0 ? n : null;
}

async function markWhatsappConversationExpiredReactive(
  admin: ReturnType<typeof createClient>,
  conversationId: string,
  orgIdHint: string | null,
): Promise<void> {
  const { data: conv } = await admin
    .from("whatsapp_conversations")
    .select("organization_id, lead_status_id")
    .eq("id", conversationId)
    .maybeSingle();
  const orgId = (conv?.organization_id as string | undefined) ?? orgIdHint;
  if (!orgId) return;

  let expiredId: string | null = null;
  const { data: orgExpired } = await admin
    .from("lead_statuses")
    .select("id")
    .eq("organization_id", orgId)
    .eq("name", "Expired")
    .maybeSingle();
  expiredId = (orgExpired?.id as string | undefined) ?? null;
  if (!expiredId) {
    const { data: g } = await admin
      .from("lead_statuses")
      .select("id")
      .is("organization_id", null)
      .eq("name", "Expired")
      .maybeSingle();
    expiredId = (g?.id as string | undefined) ?? null;
  }
  if (!expiredId) return;

  let statusName = "";
  if (conv?.lead_status_id) {
    const { data: stRow } = await admin
      .from("lead_statuses")
      .select("name")
      .eq("id", conv.lead_status_id as string)
      .maybeSingle();
    statusName = ((stRow?.name as string) ?? "").trim().toLowerCase();
  }
  if (["closed", "resolve", "lost", "converted", "expired"].includes(statusName)) return;

  const nowIso = new Date().toISOString();
  await admin
    .from("whatsapp_conversations")
    .update({ lead_status_id: expiredId, meta_session_expires_at: nowIso, updated_at: nowIso })
    .eq("id", conversationId);
}

function isResolvedStatusName(name: string | null | undefined): boolean {
  const n = (name ?? "").trim().toLowerCase();
  return n === "closed" || n === "resolve";
}

function isExpiredStatusName(name: string | null | undefined): boolean {
  return (name ?? "").trim().toLowerCase() === "expired";
}

async function resolveInProgressStatusId(
  admin: ReturnType<typeof createClient>,
  orgId: string,
): Promise<string | null> {
  const { data: orgStatus } = await admin
    .from("lead_statuses")
    .select("id")
    .eq("organization_id", orgId)
    .eq("name", "In Progress")
    .maybeSingle();
  if (orgStatus?.id) return orgStatus.id as string;
  const { data: defaultStatus } = await admin
    .from("lead_statuses")
    .select("id")
    .is("organization_id", null)
    .eq("name", "In Progress")
    .maybeSingle();
  return (defaultStatus?.id as string | undefined) ?? null;
}

const WA_TICKET_PREFIX = "WA-";

async function resolveLeadPhoneDigits(
  admin: ReturnType<typeof createClient>,
  leadId: string,
): Promise<string | null> {
  const { data: lead } = await admin
    .from("leads")
    .select("phone_number")
    .eq("id", leadId)
    .maybeSingle();
  let phone = lead?.phone_number != null ? String(lead.phone_number).trim() : "";
  if (!phone) {
    const { data: profile } = await admin
      .from("lead_client_profiles")
      .select("phone_number")
      .eq("lead_id", leadId)
      .maybeSingle();
    phone = profile?.phone_number != null ? String(profile.phone_number).trim() : "";
  }
  const digits = digitsOnly(phone);
  return digits.length >= 8 ? digits : null;
}

async function findOrCreateConversationForLead(
  admin: ReturnType<typeof createClient>,
  orgId: string,
  leadId: string,
  phoneDigits: string,
  waAccount: { id: string; phone_number_id: string },
): Promise<{ conversationId: string; ticketId: string; created: boolean } | null> {
  const { data: lead } = await admin
    .from("leads")
    .select("id, client, title, ticket_id, assignee_id, organization_id")
    .eq("id", leadId)
    .eq("organization_id", orgId)
    .maybeSingle();
  if (!lead) return null;

  const pnId = String(waAccount.phone_number_id).trim();
  const { data: existingConv } = await admin
    .from("whatsapp_conversations")
    .select("id, ticket_id")
    .eq("organization_id", orgId)
    .eq("customer_wa_id", phoneDigits)
    .eq("channel", "whatsapp")
    .eq("phone_number_id", pnId)
    .maybeSingle();

  const now = new Date().toISOString();
  const customerName = String(lead.client ?? lead.title ?? "").trim() || phoneDigits;

  if (existingConv?.id) {
    const ticketId =
      (existingConv.ticket_id as string | null)?.trim() ||
      (lead.ticket_id as string | null)?.trim() ||
      `${WA_TICKET_PREFIX}${String(existingConv.id).replace(/-/g, "").slice(0, 8).toUpperCase()}`;
    await admin
      .from("whatsapp_conversations")
      .update({
        assignee_id: lead.assignee_id ?? undefined,
        ticket_id: ticketId,
        updated_at: now,
      })
      .eq("id", existingConv.id);
    if (!(lead.ticket_id as string | null)?.trim()) {
      await admin
        .from("leads")
        .update({ ticket_id: ticketId, phone_number: phoneDigits, updated_at: now })
        .eq("id", leadId);
    }
    return { conversationId: existingConv.id as string, ticketId, created: false };
  }

  const ticketId =
    (lead.ticket_id as string | null)?.trim() ||
    `${WA_TICKET_PREFIX}${leadId.replace(/-/g, "").slice(0, 8).toUpperCase()}`;

  const { data: inserted, error: insertErr } = await admin
    .from("whatsapp_conversations")
    .insert({
      organization_id: orgId,
      customer_wa_id: phoneDigits,
      customer_external_id: phoneDigits,
      customer_name: customerName,
      channel: "whatsapp",
      phone_number_id: pnId,
      assignee_id: lead.assignee_id ?? null,
      ticket_id: ticketId,
      last_message_at: now,
      last_message_body: "",
      updated_at: now,
    })
    .select("id")
    .single();

  if (insertErr || !inserted?.id) {
    console.error("findOrCreateConversationForLead insert error:", insertErr);
    return null;
  }

  const convId = inserted.id as string;
  const finalTicket =
    ticketId || `${WA_TICKET_PREFIX}${convId.replace(/-/g, "").slice(0, 8).toUpperCase()}`;
  await admin
    .from("whatsapp_conversations")
    .update({ ticket_id: finalTicket, updated_at: now })
    .eq("id", convId);
  await admin
    .from("leads")
    .update({ ticket_id: finalTicket, phone_number: phoneDigits, updated_at: now })
    .eq("id", leadId);

  return { conversationId: convId, ticketId: finalTicket, created: true };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { status: 200, headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const token = authHeader.replace("Bearer ", "");
    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    const supabaseWithUser = createClient(supabaseUrl, serviceRoleKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const supabaseAdmin = createClient(supabaseUrl, serviceRoleKey);

    const { data: { user }, error: userError } = await supabaseWithUser.auth.getUser(token);
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("active_organization_id")
      .eq("user_id", user.id)
      .single();

    const body = await req.json().catch(() => ({}));
    let conversationId = body.conversation_id != null ? String(body.conversation_id).trim() : "";
    const leadIdParam = body.lead_id != null ? String(body.lead_id).trim() : "";
    const skipStatusGate = Boolean(leadIdParam);
    const templateName = body.template_name != null ? String(body.template_name).trim() : "";
    const templateLanguage = body.template_language != null ? String(body.template_language).trim() : "";
    const templateHsmId = body.template_hsm_id != null ? String(body.template_hsm_id).trim() : null;
    const templateComponentsJson = Array.isArray(body.template_components_json)
      ? body.template_components_json
      : [];
    const parameterValues = Array.isArray(body.parameter_values) ? body.parameter_values : [];

    if (!conversationId && !leadIdParam) {
      return new Response(
        JSON.stringify({ error: "Missing conversation_id or lead_id", code: "MISSING_TARGET" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
    if (!templateName || !templateLanguage) {
      return new Response(JSON.stringify({ error: "Missing template_name or template_language", code: "MISSING_TEMPLATE" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const orgIdFromProfile = profile?.active_organization_id as string | undefined;
    if (!orgIdFromProfile) {
      return new Response(JSON.stringify({ error: "No active organization", code: "NO_ORG" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    let resolvedLeadId: string | null = leadIdParam || null;
    let conversationCreated = false;

    if (leadIdParam && !conversationId) {
      const phoneDigits = await resolveLeadPhoneDigits(supabaseAdmin, leadIdParam);
      if (!phoneDigits) {
        return new Response(
          JSON.stringify({
            error: "Nomor telepon lead tidak ditemukan. Isi nomor di profil klien atau data lead.",
            code: "MISSING_PHONE",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      const { data: leadRow } = await supabaseAdmin
        .from("leads")
        .select("id, organization_id, assignee_id")
        .eq("id", leadIdParam)
        .maybeSingle();

      if (!leadRow || leadRow.organization_id !== orgIdFromProfile) {
        return new Response(JSON.stringify({ error: "Lead not found", code: "LEAD_NOT_FOUND" }), {
          status: 404,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      if (leadRow.assignee_id == null || String(leadRow.assignee_id).trim() === "") {
        return new Response(
          JSON.stringify({
            error: "Tetapkan agen (assignee) pada lead ini sebelum mengirim follow-up.",
            code: "ASSIGNEE_REQUIRED",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      const { data: waAccountRow } = await supabaseAdmin
        .from("organization_whatsapp_accounts")
        .select("id, phone_number_id, is_active")
        .eq("organization_id", orgIdFromProfile)
        .eq("is_active", true)
        .order("updated_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      if (!waAccountRow?.phone_number_id) {
        return new Response(
          JSON.stringify({
            error:
              "WhatsApp not configured for this organization. Connect WhatsApp in Operations → Consultant → WhatsApp Connect.",
            code: "WHATSAPP_NOT_CONFIGURED",
          }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
        );
      }

      const found = await findOrCreateConversationForLead(
        supabaseAdmin,
        orgIdFromProfile,
        leadIdParam,
        phoneDigits,
        { id: waAccountRow.id as string, phone_number_id: String(waAccountRow.phone_number_id) },
      );
      if (!found) {
        return new Response(JSON.stringify({ error: "Could not create conversation", code: "CONV_CREATE_FAILED" }), {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      conversationId = found.conversationId;
      conversationCreated = found.created;
    }

    const { data: conv } = await supabaseAdmin
      .from("whatsapp_conversations")
      .select(
        "id, organization_id, customer_wa_id, customer_name, phone_number_id, channel, assignee_id, lead_status_id, ticket_id, meta_session_expires_at",
      )
      .eq("id", conversationId)
      .maybeSingle();

    if (!conv) {
      return new Response(JSON.stringify({ error: "Conversation not found", code: "CONVERSATION_NOT_FOUND" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const orgId = conv.organization_id as string;
    if (profile?.active_organization_id !== orgId) {
      return new Response(JSON.stringify({ error: "Organization mismatch", code: "ORG_MISMATCH" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!resolvedLeadId && conv.ticket_id) {
      const { data: linkedLead } = await supabaseAdmin
        .from("leads")
        .select("id")
        .eq("organization_id", orgId)
        .eq("ticket_id", String(conv.ticket_id).trim())
        .maybeSingle();
      resolvedLeadId = (linkedLead?.id as string | undefined) ?? null;
    }

    const convChannel = String(conv.channel ?? "").toLowerCase();
    if (convChannel === "instagram") {
      return new Response(
        JSON.stringify({ error: "Follow-up template hanya untuk WhatsApp.", code: "NOT_WHATSAPP" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    if (conv.assignee_id == null || String(conv.assignee_id).trim() === "") {
      return new Response(
        JSON.stringify({
          error: "Tetapkan agen (assignee) pada percakapan ini sebelum mengirim pesan.",
          code: "ASSIGNEE_REQUIRED",
        }),
        { status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const { data: subRow } = await supabaseAdmin
      .from("organization_subscriptions")
      .select("omnichannel_paid_seat_count")
      .eq("organization_id", orgId)
      .maybeSingle();
    const paidSeats = Number(subRow?.omnichannel_paid_seat_count ?? 0);
    if (!Number.isFinite(paidSeats) || paidSeats < 1) {
      return new Response(
        JSON.stringify({
          error:
            "Add-on omnichannel belum aktif. Aktifkan atau beli seat add-on di Langganan → Paket atau Pengaturan Omnichannel untuk membalas chat.",
          code: "OMNICHANNEL_ADDON_REQUIRED",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    let statusName: string | null = null;
    if (conv.lead_status_id) {
      const { data: st } = await supabaseAdmin
        .from("lead_statuses")
        .select("name")
        .eq("id", conv.lead_status_id as string)
        .maybeSingle();
      statusName = (st?.name as string) ?? null;
    }

    const wasResolved = isResolvedStatusName(statusName);
    const wasExpired = isExpiredStatusName(statusName);

    if (!skipStatusGate && !wasResolved && !wasExpired) {
      return new Response(
        JSON.stringify({
          error: "Follow-up template hanya untuk chat Resolve atau Expired.",
          code: "INVALID_STATUS",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const pnId = conv.phone_number_id != null ? String(conv.phone_number_id).trim() : "";
    const { data: waAccount } = await supabaseAdmin
      .from("organization_whatsapp_accounts")
      .select("id, meta_access_token, phone_number_id, is_active")
      .eq("organization_id", orgId)
      .eq("phone_number_id", pnId)
      .eq("is_active", true)
      .maybeSingle();

    if (!waAccount?.phone_number_id) {
      return new Response(
        JSON.stringify({
          error:
            "WhatsApp not configured for this conversation. Connect WhatsApp in Operations → Consultant → WhatsApp Connect.",
          code: "WHATSAPP_NOT_CONFIGURED",
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    let accessToken = String(waAccount.meta_access_token ?? "").trim();
    if (!accessToken) {
      const { data: orgMeta } = await supabaseAdmin
        .from("organization_meta_config")
        .select("meta_access_token")
        .eq("organization_id", orgId)
        .maybeSingle();
      accessToken = String(orgMeta?.meta_access_token ?? "").trim();
    }
    if (!accessToken) {
      return new Response(JSON.stringify({ error: "Missing Meta access token", code: "NO_TOKEN" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const toDigits = digitsOnly(String(conv.customer_wa_id ?? ""));
    if (!toDigits) {
      return new Response(JSON.stringify({ error: "Missing customer WhatsApp number", code: "MISSING_TO" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const built = buildGraphTemplateComponents(templateComponentsJson, parameterValues, {
      allowMediaHeader: true,
    });
    if (isTemplateBuildFailure(built)) {
      return new Response(JSON.stringify({ error: built.reason, code: "TEMPLATE_COMPONENTS_INVALID" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const sendRes = await postTemplateMessage(
      String(waAccount.phone_number_id),
      accessToken,
      toDigits,
      templateName,
      templateLanguage,
      built.components,
    );

    const ticketId =
      (conv.ticket_id as string | null) ??
      `WA-${conversationId.replace(/-/g, "").slice(0, 8).toUpperCase()}`;

    if (isPostTemplateMessageFailure(sendRes)) {
      let metaMsg = sendRes.body;
      try {
        const parsed = JSON.parse(sendRes.body) as { error?: { message?: string; code?: number } };
        metaMsg = parsed?.error?.message ?? sendRes.body;
        const code = parsed?.error?.code;
        const looksLikeSessionExpired =
          Number(code) === 131047 ||
          Number(code) === 131026 ||
          /re-engagement|24 hours|outside the window|session has expired|outside of allowed window/i.test(
            String(metaMsg),
          );
        if (looksLikeSessionExpired) {
          await markWhatsappConversationExpiredReactive(supabaseAdmin, conversationId, orgId);
        }
      } catch {
        /* keep metaMsg */
      }

      await supabaseAdmin.from("whatsapp_template_followups").insert({
        organization_id: orgId,
        whatsapp_conversation_id: conversationId,
        lead_id: resolvedLeadId,
        whatsapp_account_id: waAccount.id,
        phone_number_id: String(waAccount.phone_number_id),
        customer_wa_id: toDigits,
        ticket_id: ticketId,
        template_name: templateName,
        template_language: templateLanguage,
        template_hsm_id: templateHsmId,
        parameter_values: parameterValues,
        template_components_json: templateComponentsJson,
        send_status: "failed",
        error_message: String(metaMsg).slice(0, 500),
        wa_message_id: null,
        sent_by: user.id,
      });

      return new Response(JSON.stringify({ error: String(metaMsg), code: "META_SEND_FAILED" }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const waMessageId = sendRes.wa_message_id;
    const metaData = sendRes.metaData;
    const storedBody = renderTemplateBodyPreview(templateName, templateComponentsJson, parameterValues);
    const now = new Date().toISOString();
    const lastBody = storedBody.slice(0, 200);

    const expSec = parseWabaExpirationUnixSeconds(metaData);
    if (expSec != null) {
      const expIso = new Date(expSec * 1000).toISOString();
      const prev = conv.meta_session_expires_at;
      const prevMs = prev != null && String(prev).trim() !== "" ? new Date(String(prev)).getTime() : NaN;
      if (Number.isNaN(prevMs) || prevMs < expSec * 1000) {
        await supabaseAdmin
          .from("whatsapp_conversations")
          .update({ meta_session_expires_at: expIso, updated_at: now })
          .eq("id", conversationId);
      }
    }

    const insertPayload: Record<string, unknown> = {
      conversation_id: conversationId,
      direction: "outbound",
      wa_message_id: waMessageId,
      platform_message_id: waMessageId,
      channel: "whatsapp",
      body: storedBody,
      message_type: "template",
      raw_metadata: {
        ...metaData,
        synckerja_template_followup: {
          template_name: templateName,
          template_language: templateLanguage,
          template_hsm_id: templateHsmId,
          parameter_values: parameterValues,
        },
      },
      status: "sent",
    };

    const compatibilityPayload: Record<string, unknown> = { ...insertPayload };
    const dropColumnsInOrder = ["status", "platform_message_id", "channel"] as const;
    let insertedMessage: Record<string, unknown> | null = null;
    let insertError: { code?: string; message?: string } | null = null;

    for (const col of [null, ...dropColumnsInOrder]) {
      if (col) delete compatibilityPayload[col];
      const attempt = await supabaseAdmin.from("whatsapp_messages").insert(compatibilityPayload).select().single();
      if (!attempt.error) {
        insertedMessage = (attempt.data as Record<string, unknown> | null) ?? null;
        insertError = null;
        break;
      }
      insertError = {
        code: (attempt.error as { code?: string }).code,
        message: (attempt.error as { message?: string }).message,
      };
      if (insertError.code !== "PGRST204") break;
    }

    if (insertError) {
      console.error("whatsapp_messages insert error (follow-up):", insertError);
    }

    const messageUuid = insertedMessage?.id != null ? String(insertedMessage.id) : null;

    const { data: followupRow } = await supabaseAdmin
      .from("whatsapp_template_followups")
      .insert({
        organization_id: orgId,
        whatsapp_conversation_id: conversationId,
        lead_id: resolvedLeadId,
        whatsapp_message_id: messageUuid,
        whatsapp_account_id: waAccount.id,
        phone_number_id: String(waAccount.phone_number_id),
        customer_wa_id: toDigits,
        ticket_id: ticketId,
        template_name: templateName,
        template_language: templateLanguage,
        template_hsm_id: templateHsmId,
        parameter_values: parameterValues,
        template_components_json: templateComponentsJson,
        send_status: "sent",
        error_message: null,
        wa_message_id: waMessageId,
        sent_by: user.id,
      })
      .select("id")
      .single();

    await supabaseAdmin.rpc("apply_template_followup_sent", {
      p_lead_id: resolvedLeadId,
      p_conv_id: conversationId,
    });

    let returnedLeadStatusId: string | null = null;

    await supabaseAdmin
      .from("whatsapp_conversations")
      .update({
        last_message_at: now,
        last_message_body: lastBody,
        updated_at: now,
      })
      .eq("id", conversationId);

    if (wasResolved && !wasExpired) {
      const inProgressId = await resolveInProgressStatusId(supabaseAdmin, orgId);
      if (inProgressId) {
        returnedLeadStatusId = inProgressId;
        await supabaseAdmin
          .from("whatsapp_conversations")
          .update({ lead_status_id: inProgressId, updated_at: now })
          .eq("id", conversationId);
        await supabaseAdmin
          .from("leads")
          .update({ status_id: inProgressId, updated_at: now })
          .eq("organization_id", orgId)
          .eq("ticket_id", ticketId);
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message_id: waMessageId,
        message: insertedMessage,
        followup_id: followupRow?.id ?? null,
        lead_status_id: returnedLeadStatusId ?? undefined,
        conversation_id: conversationId,
        conversation_created: conversationCreated,
        lead_id: resolvedLeadId ?? undefined,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (e) {
    console.error("send-whatsapp-template-followup error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Internal error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
