// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://najgdwffjhnqlogfrlqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hamdkd2ZmamhucWxvZ2ZybHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg3NjgsImV4cCI6MjA2NTQ4NDc2OH0.Qr10qkO19ssS8ZoF7HUULGFVLX_zeFLCFYJNyI97XHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});