import { NewLead } from '@/shared/types/leads';
import { format } from 'date-fns';
import type { LeadsFilters } from './LeadsFilters';
import { loadPdfKit } from '@/shared/lib/pdf/loadPdfKit';

export interface FilteredData {
  leads: NewLead[];
  filters: LeadsFilters;
  clientStatuses?: Record<string, 'full' | 'partial' | 'empty'>;
  clientProfiles?: Record<string, any>;
  metrics?: {
    completeDataCount: number;
    incompleteDataCount: number;
    noDataCount: number;
    hotProspectCount: number;
    warmProspectCount: number;
    coldProspectCount: number;
    sourceAnalysis: Array<{source: string, count: number, percentage: number}>;
    servicesAnalysis: Array<{service: string, count: number}>;
    locationAnalysis: Array<{location: string, count: number}>;
    statusAnalysis: Array<{status: string, count: number}>;
    employeeAnalysis: Array<{employee: string, totalLeads: number, convertedLeads: number, conversionRate: number}>;
  };
}

export const generateLeadsPDF = async (data: FilteredData): Promise<void> => {
  const { jsPDF } = await loadPdfKit();
  const doc = new jsPDF();
  
  // Page settings
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const maxY = pageHeight - 20; // Leave smaller space for footer
  
  // Helper function to check if we need a new page
  const checkPageBreak = (currentY: number, neededSpace: number = 20) => {
    if (currentY + neededSpace > maxY) {
      doc.addPage();
      return margin + 10; // Reset Y position with smaller top margin
    }
    return currentY;
  };
  
  // Helper function to add page footer
  const addPageFooter = () => {
    const pageNum = doc.getCurrentPageInfo().pageNumber;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${pageNum} | Generated by Profiloop App`, doc.internal.pageSize.width / 2, pageHeight - 10, { align: 'center' });
  };
  
  // Use pre-calculated metrics if available, otherwise calculate
  const totalLeads = data.leads.length;
  
  // Data completeness analysis using metrics or calculated values
  const completeData = data.metrics?.completeDataCount ?? 0;
  const incompleteData = data.metrics?.incompleteDataCount ?? 0;
  const noData = data.metrics?.noDataCount ?? 0;
  
  // Priority analysis using metrics
  const hotProspects = data.metrics?.hotProspectCount ?? 0;
  const warmProspects = data.metrics?.warmProspectCount ?? 0;
  const coldProspects = data.metrics?.coldProspectCount ?? 0;
  
  // Source analysis using metrics
  const sourceAnalysis = data.metrics?.sourceAnalysis ?? [];
  const websiteLeads = sourceAnalysis.find(s => s.source === 'Website')?.count ?? 0;
  const emailLeads = sourceAnalysis.find(s => s.source === 'Email')?.count ?? 0;
  const phoneLeads = sourceAnalysis.find(s => s.source === 'Phone')?.count ?? 0;
  const chatLeads = sourceAnalysis.find(s => s.source === 'Chat')?.count ?? 0;
  const whatsappLeads = sourceAnalysis.find(s => s.source === 'WhatsApp')?.count ?? 0;
  
  // Services analysis using metrics
  const servicesData = data.metrics?.servicesAnalysis?.map(s => ({
    name: s.service,
    count: s.count
  })) ?? [];
  
  // Location analysis using metrics
  const locationsData = data.metrics?.locationAnalysis?.map(l => ({
    name: l.location,
    count: l.count
  })) ?? [];
  
  // Status analysis using metrics  
  const statusAnalysis = data.metrics?.statusAnalysis ?? [];
  const inProgressLeads = statusAnalysis.find(s => s.status === 'In Progress')?.count ?? 0;
  const openLeads = statusAnalysis.find(s => s.status === 'Open')?.count ?? 0;
  const closedLeads = statusAnalysis.find(s => s.status === 'Closed')?.count ?? 0;

  let yPos = margin;
  
  // Header
  doc.setFontSize(22);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('Leads Report Summary', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  
  // Generate date text based on filter
  let dateText = '';
  if (data.filters?.dateRange?.from && data.filters?.dateRange?.to) {
    const fromDate = format(new Date(data.filters.dateRange.from), 'dd MMMM yyyy');
    const toDate = format(new Date(data.filters.dateRange.to), 'dd MMMM yyyy');
    dateText = `${fromDate} - ${toDate}`;
  } else {
    dateText = `All Data (Generated: ${format(new Date(), 'dd MMMM yyyy')})`;
  }
  
  doc.text(dateText, 20, yPos);
  yPos += 6;
  
  // Add horizontal line
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(1);
  doc.line(20, yPos, 190, yPos);
  yPos += 15;
  
  // LEAD SOURCE section
  yPos = checkPageBreak(yPos, 30);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('LEAD SOURCE:', 20, yPos);
  yPos += 8;
  
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  if (websiteLeads > 0) {
    doc.text(`Website: ${websiteLeads}`, 20, yPos);
    yPos += 6;
  }
  if (emailLeads > 0) {
    doc.text(`Email: ${emailLeads}`, 20, yPos);
    yPos += 6;
  }
  if (phoneLeads > 0) {
    doc.text(`Phone: ${phoneLeads}`, 20, yPos);
    yPos += 6;
  }
  if (chatLeads > 0) {
    doc.text(`Chat: ${chatLeads}`, 20, yPos);
    yPos += 6;
  }
  if (whatsappLeads > 0) {
    doc.text(`WhatsApp: ${whatsappLeads}`, 20, yPos);
    yPos += 6;
  }
  yPos += 8;
  
  // DATA SUMMARY section
  yPos = checkPageBreak(yPos, 35);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('DATA SUMMARY', 20, yPos);
  yPos += 10;
  
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  doc.text(`Complete Data: ${completeData}`, 20, yPos);
  yPos += 8;
  doc.text(`Incomplete Data: ${incompleteData}`, 20, yPos);
  yPos += 8;
  doc.text(`No Data: ${noData}`, 20, yPos);
  yPos += 12;
  
  // SERVICE section
  if (servicesData.length > 0) {
    yPos = checkPageBreak(yPos, 25);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text('SERVICE', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    doc.setTextColor(130, 130, 130);
    servicesData.forEach(service => {
      yPos = checkPageBreak(yPos, 8);
      doc.text(`${service.name}: ${service.count}`, 20, yPos);
      yPos += 6;
    });
    yPos += 8;
  } else {
    // Default SERVICE section if no services data
    yPos = checkPageBreak(yPos, 25);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text('SERVICE', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    doc.setTextColor(130, 130, 130);
    doc.text('Kelamin: 0', 20, yPos);
    yPos += 12;
  }
  
  // LOCATION section (separate from SERVICE)
  yPos = checkPageBreak(yPos, 25);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('LOCATION', 20, yPos);
  yPos += 10;
  
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  if (locationsData.length > 0) {
    locationsData.forEach(location => {
      yPos = checkPageBreak(yPos, 8);
      doc.text(`${location.name}: ${location.count}`, 20, yPos);
      yPos += 6;
    });
  } else {
    // Default location data if no locations
    doc.text('Jakarta: 1', 20, yPos);
    yPos += 6;
    doc.text('Unknown: 1', 20, yPos);
    yPos += 6;
  }
  yPos += 15; // Add extra spacing before Priority Analysis
  
  // Leads Priority Analysis section
  yPos = checkPageBreak(yPos, 45);
  doc.setFontSize(14);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Leads Priority Analysis', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  doc.text(`Hot Prospect: ${hotProspects}`, 20, yPos);
  yPos += 8;
  doc.text(`Warm Prospect: ${warmProspects}`, 20, yPos);
  yPos += 8;
  doc.text(`Cold Prospect: ${coldProspects}`, 20, yPos);
  yPos += 20;
  
  // STATUS section
  yPos = checkPageBreak(yPos, 30);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('STATUS', 20, yPos);
  yPos += 10;
  
  doc.setFont(undefined, 'normal');
  doc.setTextColor(130, 130, 130);
  doc.text(`On going: ${inProgressLeads}`, 20, yPos);
  if (openLeads > 0) {
    yPos += 6;
    doc.text(`Open: ${openLeads}`, 20, yPos);
  }
  if (closedLeads > 0) {
    yPos += 6;
    doc.text(`Resolve: ${closedLeads}`, 20, yPos);
  }
  
  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} | Generated by Profiloop App`, doc.internal.pageSize.width / 2, pageHeight - 10, { align: 'center' });
  }
  
  // Save the PDF
  const fileName = `Report_Summary_${format(new Date(), 'yyyy-MM-dd_HH-mm')}.pdf`;
  doc.save(fileName);
};
