export const STOCK_MANAGEMENT_BASE_PATH = "/operations/sales/stock-management";
export const STOCK_MANAGEMENT_DASHBOARD_PATH = STOCK_MANAGEMENT_BASE_PATH;
export const STOCK_MANAGEMENT_MAPPING_PATH = `${STOCK_MANAGEMENT_BASE_PATH}/mapping`;
export const STOCK_MANAGEMENT_SYNC_LOGS_PATH = `${STOCK_MANAGEMENT_BASE_PATH}/sync-logs`;

export const STOCK_MANAGEMENT_PAGE_PATH = STOCK_MANAGEMENT_BASE_PATH;
