/** i18n keys for Synckerja POS settings screen. */
export const POS_SETTINGS_I18N = {
  title: "posSettings.title",
  onlineOrdersTitle: "posSettings.onlineOrdersTitle",
  paymentTitle: "posSettings.paymentTitle",
  taxTitle: "posSettings.taxTitle",
  surchargeTitle: "posSettings.surchargeTitle",
  paymentSettingsTitle: "posSettings.paymentSettingsTitle",
  sectionOnlineOrders: "posSettings.sectionOnlineOrders",
  sectionPayment: "posSettings.sectionPayment",
  navOnlineOrderSettings: "posSettings.navOnlineOrderSettings",
  navPayment: "posSettings.navPayment",
  navTax: "posSettings.navTax",
  navSurcharge: "posSettings.navSurcharge",
  navPaymentSettings: "posSettings.navPaymentSettings",
  statusActive: "posSettings.statusActive",
  receiveSection: "posSettings.receiveSection",
  deviceOnlineOrders: "posSettings.deviceOnlineOrders",
  deviceOnlineOrdersHint: "posSettings.deviceOnlineOrdersHint",
  notifSection: "posSettings.notifSection",
  sound: "posSettings.sound",
  notificationSound: "posSettings.notificationSound",
  paymentSoon: "posSettings.paymentSoon",
  soundSheetTitle: "posSettings.soundSheetTitle",
  soundTelepathy: "posSettings.sounds.telepathy",
  soundChime: "posSettings.sounds.chime",
  soundPing: "posSettings.sounds.ping",
  soundBell: "posSettings.sounds.bell",
  menu: "posSettings.menu",
  paymentTermsBefore: "posSettings.payment.termsBefore",
  paymentTermsLink: "posSettings.payment.termsLink",
  paymentTermsAfter: "posSettings.payment.termsAfter",
  paymentDigitalSection: "posSettings.payment.digitalSection",
  paymentActiveMethods: "posSettings.payment.activeMethods",
  paymentActiveMethodsHint: "posSettings.payment.activeMethodsHint",
  paymentActiveMethodsEmpty: "posSettings.payment.activeMethodsEmpty",
  paymentQrisName: "posSettings.payment.qrisName",
  paymentQrisStatusReady: "posSettings.payment.qrisStatus.ready",
  paymentSandboxBadge: "posSettings.payment.sandboxBadge",
  paymentEmptyState: "posSettings.payment.emptyState",
  taxToggleLabel: "posSettings.tax.toggleLabel",
  taxEmpty: "posSettings.tax.empty",
  taxSaveError: "posSettings.tax.saveError",
  surchargeToggleLabel: "posSettings.surcharge.toggleLabel",
  surchargeEmpty: "posSettings.surcharge.empty",
  surchargeSaveError: "posSettings.surcharge.saveError",
  paymentSettingsTaxGratuityRow: "posSettings.paymentSettings.taxGratuityRow",
  paymentSettingsPricesExclude: "posSettings.paymentSettings.pricesExclude",
  paymentSettingsPricesInclude: "posSettings.paymentSettings.pricesInclude",
  paymentSettingsEmployeeMonitor: "posSettings.paymentSettings.employeeMonitor",
  paymentSettingsMethodSheetTitle: "posSettings.paymentSettings.methodSheetTitle",
  paymentSettingsMethodAdd: "posSettings.paymentSettings.methodAdd",
  paymentSettingsMethodInclude: "posSettings.paymentSettings.methodInclude",
  paymentSettingsManageTax: "posSettings.paymentSettings.manageTax",
  paymentSettingsManageSurcharge: "posSettings.paymentSettings.manageSurcharge",
  paymentSettingsSaveError: "posSettings.paymentSettings.saveError",
  paymentSettingsMethodHintAdd: "posSettings.paymentSettings.methodHintAdd",
  paymentSettingsMethodHintInclude: "posSettings.paymentSettings.methodHintInclude",
  sectionHardware: "posSettings.sectionHardware",
  navPrinter: "posSettings.navPrinter",
  navBarcodeScanner: "posSettings.navBarcodeScanner",
  navGobizEdc: "posSettings.navGobizEdc",
  navCustomerDisplay: "posSettings.navCustomerDisplay",
  printerTitle: "posSettings.printerTitle",
  barcodeScannerTitle: "posSettings.barcodeScannerTitle",
  gobizEdcTitle: "posSettings.gobizEdcTitle",
  customerDisplayTitle: "posSettings.customerDisplayTitle",
  hardwareSoon: "posSettings.hardwareSoon",
  printerAvailable: "posSettings.printer.available",
  printerRefresh: "posSettings.printer.refresh",
  printerInactive: "posSettings.printer.inactive",
  printerEmpty: "posSettings.printer.empty",
  printerNickname: "posSettings.printer.nickname",
  printerCancel: "posSettings.printer.cancel",
  printerSave: "posSettings.printer.save",
  printerPrintFromDevice: "posSettings.printer.printFromDevice",
  printerRoleReceiptBill: "posSettings.printer.roleReceiptBill",
  printerRoleOrderTicket: "posSettings.printer.roleOrderTicket",
  printerRoleSticker: "posSettings.printer.roleSticker",
  printerRoleQueue: "posSettings.printer.roleQueue",
  printerRoleShift: "posSettings.printer.roleShift",
  printerRoleShortReceipt: "posSettings.printer.roleShortReceipt",
  printerRoleShortTicket: "posSettings.printer.roleShortTicket",
  printerRoleShortSticker: "posSettings.printer.roleShortSticker",
  printerRoleShortQueue: "posSettings.printer.roleShortQueue",
  printerRoleShortShift: "posSettings.printer.roleShortShift",
  printerNotAvailable: "posSettings.printer.notAvailable",
  printerStickerHint: "posSettings.printer.stickerHint",
  printerTicketSection: "posSettings.printer.ticketSection",
  printerTicketCopies: "posSettings.printer.ticketCopies",
  printerTicketOnPay: "posSettings.printer.ticketOnPay",
  printerTicketPerProduct: "posSettings.printer.ticketPerProduct",
  printerTicketPerProductHint: "posSettings.printer.ticketPerProductHint",
  printerTicketCategories: "posSettings.printer.ticketCategories",
  printerTicketCategoriesTitle: "posSettings.printer.ticketCategoriesTitle",
  printerBluetoothTitle: "posSettings.printer.bluetoothTitle",
  printerBluetoothOn: "posSettings.printer.bluetoothOn",
  printerBluetoothOff: "posSettings.printer.bluetoothOff",
  printerBluetoothUnavailable: "posSettings.printer.bluetoothUnavailable",
  printerBluetoothScanning: "posSettings.printer.bluetoothScanning",
  printerBluetoothEmpty: "posSettings.printer.bluetoothEmpty",
  printerBluetoothDone: "posSettings.printer.bluetoothDone",
  printerBluetoothDetails: "posSettings.printer.bluetoothDetails",
  printerCopiesDone: "posSettings.printer.copiesDone",
  printerConnectError: "posSettings.printer.connectError",
  printerPrintError: "posSettings.printer.printError",
  printerPrintOk: "posSettings.printer.printOk",
  printerTicketPrinted: "posSettings.printer.ticketPrinted",
  printerBillPrinted: "posSettings.printer.billPrinted",
  printerNoReceiptPrinter: "posSettings.printer.noReceiptPrinter",
  printerNoTicketPrinter: "posSettings.printer.noTicketPrinter",
  printerTicketSkippedOnPay: "posSettings.printer.ticketSkippedOnPay",
  sectionAccount: "posSettings.sectionAccount",
  navLanguage: "posSettings.navLanguage",
  navProfile: "posSettings.navProfile",
  navSupport: "posSettings.navSupport",
  languageTitle: "posSettings.languageTitle",
  profileTitle: "posSettings.profileTitle",
  supportTitle: "posSettings.supportTitle",
  languageOptionId: "posSettings.language.optionId",
  languageOptionEn: "posSettings.language.optionEn",
  logout: "posSettings.logout",
  profileBusinessName: "posSettings.profile.businessName",
  profileAddress: "posSettings.profile.address",
  profileLogo: "posSettings.profile.logo",
  profileLogoHint: "posSettings.profile.logoHint",
  profileLogoRemove: "posSettings.profile.logoRemove",
  profileProvince: "posSettings.profile.province",
  profileCity: "posSettings.profile.city",
  profilePostalCode: "posSettings.profile.postalCode",
  profilePhone: "posSettings.profile.phone",
  profileStatus: "posSettings.profile.status",
  profileStatusActive: "posSettings.profile.statusActive",
  profileStatusInactive: "posSettings.profile.statusInactive",
  profileSave: "posSettings.profile.save",
  profileEdit: "posSettings.profile.edit",
  profileCancel: "posSettings.profile.cancel",
  profileSaved: "posSettings.profile.saved",
  profileSaveFailed: "posSettings.profile.saveFailed",
  profileValidation: "posSettings.profile.validation",
  profileMissingOutlet: "posSettings.profile.missingOutlet",
  profileSelectOutlet: "posSettings.profile.selectOutlet",
  profileLoading: "posSettings.profile.loading",
  profileEmptyAddress: "posSettings.profile.emptyAddress",
} as const;

export const POS_NOTIFICATION_SOUND_OPTIONS = [
  { id: "telepathy", labelKey: POS_SETTINGS_I18N.soundTelepathy, fallback: "Telepathy" },
  { id: "chime", labelKey: POS_SETTINGS_I18N.soundChime, fallback: "Chime" },
  { id: "ping", labelKey: POS_SETTINGS_I18N.soundPing, fallback: "Ping" },
  { id: "bell", labelKey: POS_SETTINGS_I18N.soundBell, fallback: "Bell" },
] as const;

export type PosNotificationSoundId = (typeof POS_NOTIFICATION_SOUND_OPTIONS)[number]["id"];

/** Public terms URL for digital payment notice (opens in new tab). */
export const POS_PAYMENT_TERMS_HREF = "/policy/terms";
