export const ORDER_CHECKOUT_I18N = {
  orderTitle: "synckerjaOrder.checkout.orderTitle",
  back: "synckerjaOrder.checkout.back",
  orderType: "synckerjaOrder.checkout.orderType",
  dineIn: "synckerjaOrder.checkout.dineIn",
  takeAway: "synckerjaOrder.checkout.takeAway",
  fromTable: "synckerjaOrder.checkout.fromTable",
  fulfillmentMismatch: "synckerjaOrder.checkout.fulfillmentMismatch",
  relatedMenu: "synckerjaOrder.checkout.relatedMenu",
  orderedItems: "synckerjaOrder.checkout.orderedItems",
  addItem: "synckerjaOrder.checkout.addItem",
  edit: "synckerjaOrder.store.cartSheet.edit",
  noNotes: "synckerjaOrder.store.cartSheet.noNotes",
  billNotes: "synckerjaOrder.checkout.billNotes",
  billNotesPlaceholder: "synckerjaOrder.checkout.billNotesPlaceholder",
  paymentDetails: "synckerjaOrder.checkout.paymentDetails",
  subtotal: "synckerjaOrder.checkout.subtotal",
  otherFees: "synckerjaOrder.checkout.otherFees",
  total: "synckerjaOrder.checkout.total",
  totalPayment: "synckerjaOrder.checkout.totalPayment",
  continueToPayment: "synckerjaOrder.checkout.continueToPayment",
  paymentTitle: "synckerjaOrder.checkout.paymentTitle",
  customerInfo: "synckerjaOrder.checkout.customerInfo",
  fullName: "synckerjaOrder.checkout.fullName",
  phone: "synckerjaOrder.checkout.phone",
  email: "synckerjaOrder.checkout.email",
  tableNumber: "synckerjaOrder.checkout.tableNumber",
  orderedFrom: "synckerjaOrder.checkout.orderedFrom",
  paymentMethod: "synckerjaOrder.checkout.paymentMethod",
  onlinePayment: "synckerjaOrder.checkout.onlinePayment",
  payCashier: "synckerjaOrder.store.payCashier",
  completePayment: "synckerjaOrder.checkout.completePayment",
  qris: "synckerjaOrder.checkout.qris",
  cashierHint: "synckerjaOrder.checkout.cashierHint",
  pay: "synckerjaOrder.checkout.pay",
  continue: "synckerjaOrder.checkout.continue",
  nameRequired: "synckerjaOrder.checkout.nameRequired",
  addItemAria: "synckerjaOrder.store.addItem",
} as const;

export type OrderCheckoutStep = "review" | "payment";
